apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-custom-resources-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-custom-resources
subjects:
  - kind: ServiceAccount
    name: crossplane
    namespace: crossplane-system
